services:
  - type: web
    name: ghostech-recrutement-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_USER
        value: ghostech92@gmail.com
      - key: RECIPIENT_EMAIL
        value: ghostech92@gmail.com
      - key: PORT
        value: 3000
      - key: EMAIL_PASS
        sync: false
